"""create category table

Revision ID: 1476cc6be768
Revises: 882b549d64b2
Create Date: 2025-09-02 02:49:00.070106

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "1476cc6be768"
down_revision: Union[str, Sequence[str], None] = "882b549d64b2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "categories",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("slug", sa.String(length=255), nullable=False),
        sa.Column("parent_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["categories.id"],
            name=op.f("fk_categories_parent_id_categories"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_categories")),
        sa.UniqueConstraint("name", name=op.f("uq_categories_name")),
        sa.UniqueConstraint("slug", name=op.f("uq_categories_slug")),
    )
    op.drop_constraint(
        op.f("supplements_name_key"), "supplements", type_="unique"
    )
    op.create_unique_constraint(
        op.f("uq_supplements_name"), "supplements", ["name"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("uq_supplements_name"), "supplements", type_="unique"
    )
    op.create_unique_constraint(
        op.f("supplements_name_key"),
        "supplements",
        ["name"],
        postgresql_nulls_not_distinct=False,
    )
    op.drop_table("categories")
    # ### end Alembic commands ###
