"""create marketplaces and supplement_offers tables

Revision ID: 2369375a4590
Revises: faecc2bbb4c4
Create Date: 2025-09-26 16:54:15.402599

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "2369375a4590"
down_revision: Union[str, Sequence[str], None] = "faecc2bbb4c4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "marketplaces",
        sa.PrimaryKeyConstraint("id", name=op.f("pk_marketplaces")),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("url", sa.Text(), nullable=True),
        sa.Column("logo", sa.Text(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.UniqueConstraint("logo", name=op.f("uq_marketplaces_logo")),
        sa.UniqueConstraint("url", name=op.f("uq_marketplaces_url")),
    )
    op.create_table(
        "supplement_offers",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("supplement_id", sa.Integer(), nullable=False),
        sa.Column("marketplace_id", sa.Integer(), nullable=True),
        sa.Column("url", sa.Text(), nullable=False),
        sa.Column("price", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("last_seen_at", sa.DateTime(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["marketplace_id"],
            ["marketplaces.id"],
            name=op.f("fk_supplement_offers_marketplace_id_marketplaces"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["supplement_id"],
            ["supplements.id"],
            name=op.f("fk_supplement_offers_supplement_id_supplements"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_supplement_offers")),
        sa.UniqueConstraint(
            "supplement_id",
            "marketplace_id",
            name="uq_offer_supplement_marketplace",
        ),
        sa.UniqueConstraint("url", name=op.f("uq_supplement_offers_url")),
    )
    op.create_index(
        op.f("ix_supplement_offers_marketplace_id"),
        "supplement_offers",
        ["marketplace_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_supplement_offers_supplement_id"),
        "supplement_offers",
        ["supplement_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_supplement_offers_supplement_id"),
        table_name="supplement_offers",
    )
    op.drop_index(
        op.f("ix_supplement_offers_marketplace_id"),
        table_name="supplement_offers",
    )
    op.drop_table("supplement_offers")
    op.drop_table("marketplaces")
    # ### end Alembic commands ###
