"""table supplement edited and table source corrected

Revision ID: 5759c611453d
Revises: fc4acfc94f6e
Create Date: 2025-09-04 02:19:42.813619

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "5759c611453d"
down_revision: Union[str, Sequence[str], None] = "fc4acfc94f6e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "sources",
        "picture",
        existing_type=sa.VARCHAR(),
        type_=sa.Text(),
        existing_nullable=True,
    )
    op.add_column(
        "supplements", sa.Column("category_id", sa.Integer(), nullable=True)
    )
    op.add_column(
        "supplements",
        sa.Column("manufacturer_id", sa.Integer(), nullable=True),
    )
    op.add_column(
        "supplements", sa.Column("comment", sa.Text(), nullable=True)
    )
    op.add_column(
        "supplements", sa.Column("picture", sa.Text(), nullable=True)
    )
    op.add_column(
        "supplements",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.add_column(
        "supplements",
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
    )
    op.create_foreign_key(
        op.f("fk_supplements_category_id_categories"),
        "supplements",
        "categories",
        ["category_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        op.f("fk_supplements_manufacturer_id_manufacturers"),
        "supplements",
        "manufacturers",
        ["manufacturer_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_supplements_manufacturer_id_manufacturers"),
        "supplements",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("fk_supplements_category_id_categories"),
        "supplements",
        type_="foreignkey",
    )
    op.drop_column("supplements", "updated_at")
    op.drop_column("supplements", "created_at")
    op.drop_column("supplements", "picture")
    op.drop_column("supplements", "comment")
    op.drop_column("supplements", "manufacturer_id")
    op.drop_column("supplements", "category_id")
    op.alter_column(
        "sources",
        "picture",
        existing_type=sa.Text(),
        type_=sa.VARCHAR(),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
